--- #trifecta bot
server:   irc.vmware.com
channels:
       - '#trifecta'
nick:     Hal
user:     trifecta

plugins:
      -
        name: 'Admin'
        config:
          file: 'admin.yml'
      -
        name: 'Identify'
        config:
          :password: "trifecta"
          :type: :nickserv