--- #trifecta bot
server:   irc.vmware.com
channels:
       - '#trifecta'
nick:     Hal
user:     trifecta

plugins:
      Admin:
        config:
          :file: 'etc/admin.yml'
      Identify:
        config:
          :password: "trifecta"
          :type: :nickserv
      Food:
        config:
          :consumer_key: dclWsywsMA11Avy8taoXTQ
          :consumer_secret: SAE4wThPXuDIEdmLAabpJSYzzxI
          :token: HbgAih-81saJ5xVr3Q6sk218O4xTu7WO
          :token_secret: dVxvKa9Lvt1Sm3Gpkyy4pT5VeyE
      Greeting:
        config:
      Dictionary:
        config:
          :api_key: 24fedade-20f8-4cc4-9c55-ac5aea4a1e37
      Search:
        config:
      Seen:
        config:
          :file: 'etc/seenlog.dat'
      Spelling:
        config:
        