--- #trifecta bot
server:   irc.vmware.com
channels:
       - '#trifecta'
       - '#pentogonal'
nick:     Hal
user:     trifecta

plugins:
      Adventure:
        config:
          :path: '/home/bot/games/'
      Admin:
        config:
          :file: 'etc/admin.yml'
          :chanserv: ChanServ@hybserv.eng.vmware.com
      Identify:
        config:
          :password: "trifecta"
          :type: :nickserv
      Food:
        config:
          :consumer_key: dclWsywsMA11Avy8taoXTQ
          :consumer_secret: SAE4wThPXuDIEdmLAabpJSYzzxI
          :token: HbgAih-81saJ5xVr3Q6sk218O4xTu7WO
          :token_secret: dVxvKa9Lvt1Sm3Gpkyy4pT5VeyE
      Greeting:
        config:
      Dictionary:
        config:
          :api_key: 24fedade-20f8-4cc4-9c55-ac5aea4a1e37
      Search:
        config:
      Seen:
        config:
          :file: 'etc/seenlog.dat'
      Spelling:
        config:
      Preview:
        config:
          :token: fb8c857d8fa50f8c13b0ea06436d69a8004bb8f7
      Shepherd:
        config:
          :bot_name: Confucious
          :botify_url: http://127.0.0.1/botify.cgi
